name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do código do repositório
      - name: Check out repository code
        uses: actions/checkout@v5

      # 2. Configurar a versão do Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      # 3. Instalar e configurar o Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.8.3
          poetry --version

      # 4. Instalar dependências do projeto via Poetry
      - name: Install dependencies
        run: |
          poetry install

      # 5. Rodar os testes Django
      - name: Run Django tests
        run: |
          poetry run python manage.py test

      # 6. Listar arquivos do workspace (opcional, para debug)
      - name: List files in repository
        run: |
          ls ${{ github.workspace }}

